server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newenvironment?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 10MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB
  #热部署配置
  devtools:
    restart:
      enabled: true  #开启热部署
  jpa:
    hibernate:
      ddl-auto: validate

#mybatis配置
mybatis:
  type-aliases-package: com.xdmd.environment.*.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰转换

# 配置pageHelper分页插件的内容
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#简单日志配置
logging:
  level:
    root: INFO
    org.springframework.web: debug
  file: D:\\xdmd_hbkj\\hbkt.log
